export const ASS_SUBTITLE_RENDERERS = Object.freeze({
	AUTO: 'auto',
	LIGHTWEIGHT: 'lightweight',
	LIBASS: 'libass',
	LIBASS_MANUAL: 'libass-manual',
	JASSUB: 'jassub',
	JASSUB_MANUAL: 'jassub-manual',
	ASSJS: 'assjs',
	BURN_IN: 'burn-in'
});

export const STABLE_ASS_SUBTITLE_RENDERER_VALUES = Object.freeze([
	ASS_SUBTITLE_RENDERERS.AUTO,
	ASS_SUBTITLE_RENDERERS.LIGHTWEIGHT,
	ASS_SUBTITLE_RENDERERS.LIBASS,
	ASS_SUBTITLE_RENDERERS.LIBASS_MANUAL,
	ASS_SUBTITLE_RENDERERS.JASSUB,
	ASS_SUBTITLE_RENDERERS.JASSUB_MANUAL,
	ASS_SUBTITLE_RENDERERS.ASSJS,
	ASS_SUBTITLE_RENDERERS.BURN_IN
]);

export const EXPERIMENTAL_ASS_SUBTITLE_RENDERER_VALUES = Object.freeze([
	ASS_SUBTITLE_RENDERERS.LIBASS,
	ASS_SUBTITLE_RENDERERS.LIBASS_MANUAL,
	ASS_SUBTITLE_RENDERERS.JASSUB,
	ASS_SUBTITLE_RENDERERS.JASSUB_MANUAL,
	ASS_SUBTITLE_RENDERERS.ASSJS
]);

export const ALL_ASS_SUBTITLE_RENDERER_VALUES = STABLE_ASS_SUBTITLE_RENDERER_VALUES;

export const normalizeAssSubtitleRenderer = (value) => {
	const normalized = String(value || '').trim().toLowerCase();
	return ALL_ASS_SUBTITLE_RENDERER_VALUES.includes(normalized)
		? normalized
		: ASS_SUBTITLE_RENDERERS.AUTO;
};
